
name: logmonitor_flutter
description: The official Flutter SDK for Logmonitor.io. See your production logs in real-time, just like your local console.
version: 0.0.1
homepage: https://logmonitor.io
repository: https://github.com/panarastudios/logmonitor_flutter # IMPORTANT
issue_tracker: https://github.com/panarastudios/logmonitor_flutter/issues # IMPORTANT

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  logging: ^1.3.0
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
